version: "3.9"

services:
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    env_file:
      - .env
    volumes:
      - ./orchestrator:/app
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
    command: python main.py

  performance:
    build: ./performance
    container_name: performance
    env_file:
      - .env
    volumes:
      - ./performance:/app
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app
    depends_on:
        - redis
    command: python performance_agent.py

  architecture:
    build: ./architecture
    container_name: architecture
    env_file:
      - .env
    volumes:
      - ./architecture:/app
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app
    depends_on:
        - redis
    command: python architecture_agent.py

  style:
    build: ./style
    container_name: style
    env_file:
      - .env
    volumes:
      - ./style:/app
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app
    depends_on:
        - redis
    command: python style_agent.py

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

# version: "3.9"

# services:
#   orchestrator:
#     build: ./orchestrator
#     container_name: orchestrator
#     depends_on:
#       - redis
#     command: python main.py

#   performance:
#     build: ./performance
#     container_name: performance
#     depends_on:
#         - redis
#     command: python performance_agent.py

#   security:
#     build: ./security
#     container_name: security
#     depends_on:
#         - redis
#     command: python security_agent.py

#   style:
#     build: ./style
#     container_name: style
#     depends_on:
#         - redis
#     command: python style_agent.py
#   redis:
#     image: redis:7-alpine
#     container_name: redis
#     ports:
#       - "6379:6379"